import BillGroup from "./model.js";

/**
 * @desc    Create new Bill Group
 * @route   POST /api/bill-group
 */
export const createBillGroup = async (req, res) => {
  try {
    const { name, ledger, subLedger, description } = req.body;

    if (!name || !ledger || !subLedger) {
      return res.status(400).json({
        success: false,
        message: "Name, Ledger, and SubLedger are required",
      });
    }

    // Code will be auto-generated by pre-save hook
    const billGroup = await BillGroup.create({
      name,
      ledger,
      subLedger,
      description,
    });

    res.status(201).json({
      success: true,
      message: "Bill Group created successfully",
      data: billGroup,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

/**
 * @desc    Get all Bill Groups (non-deleted)
 * @route   GET /api/bill-group
 */
export const getAllBillGroups = async (req, res) => {
  try {
    const billGroups = await BillGroup.find({ deleted: false })
      .populate("ledger", "name ledgerType")
      .populate("subLedger", "name")
      .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      data: billGroups,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

/**
 * @desc    Get Bill Group by ID
 * @route   GET /api/bill-group/:id
 */
export const getBillGroupById = async (req, res) => {
  try {
    const billGroup = await BillGroup.findOne({
      _id: req.params.id,
      deleted: false,
    })
      .populate("ledger", "name ledgerType")
      .populate("subLedger", "name");

    if (!billGroup) {
      return res.status(404).json({
        success: false,
        message: "Bill Group not found",
      });
    }

    res.status(200).json({
      success: true,
      data: billGroup,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

/**
 * @desc    Update Bill Group
 * @route   PUT /api/bill-group/:id
 */
export const updateBillGroup = async (req, res) => {
  try {
    const { name, ledger, subLedger, description } = req.body;

    const billGroup = await BillGroup.findByIdAndUpdate(
      req.params.id,
      { name, ledger, subLedger, description },
      { new: true, runValidators: true }
    )
      .populate("ledger", "name ledgerType")
      .populate("subLedger", "name");

    if (!billGroup) {
      return res.status(404).json({
        success: false,
        message: "Bill Group not found",
      });
    }

    res.status(200).json({
      success: true,
      message: "Bill Group updated successfully",
      data: billGroup,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

/**
 * @desc    Soft Delete Bill Group
 * @route   DELETE /api/bill-group/:id
 */
export const deleteBillGroup = async (req, res) => {
  try {
    const billGroup = await BillGroup.findByIdAndUpdate(
      req.params.id,
      { deleted: true },
      { new: true }
    );

    if (!billGroup) {
      return res.status(404).json({
        success: false,
        message: "Bill Group not found",
      });
    }

    res.status(200).json({
      success: true,
      message: "Bill Group deleted successfully",
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};
