import express from "express";
import cors from "cors";
import helmet from "helmet";
import "express-async-errors";
import authRoutes from "./modules/Auth/routes.js";
import roleRoutes from "./modules/master/role/routes.js";
import prefixRoutes from "./modules/master/prefix/routes.js";
import diplomaRoutes from "./modules/master/diploma/routes.js";
import graduationRoutes from "./modules/master/graduation/routes.js";
import postGraduationRoutes from "./modules/master/PostGraduation/routes.js";
import SuperSpecializationRoutes from "./modules/master/SuperSpecialization/routes.js";
import councilRoutes from "./modules/master/Councils/routes.js";
import departmentTypeRoutes from "./modules/master/department-type/routes.js";
import departmentSubTypeRoutes from "./modules/master/department-sub-type/routes.js";
import departmentRoutes from "./modules/master/department/routes.js";
import designationRoutes from "./modules/master/designation/routes.js";
import userRoutes from "./modules/User/routes.js";
import ledgerRoutes from "./modules/master/ledger/routes.js";
import subLedgerRoutes from "./modules/master/sub-ledger/routes.js";
import paymentModeRoutes from "./modules/master/payment-mode/routes.js";
import payeeCategoryRoutes from "./modules/master/payee-category/routes.js";
// import serviceGroupRoutes from "./modules/master/service-group/routes.js";
import billGroupRoutes from "./modules/master/bill-group/routes.js";
import serviceListRoutes from "./modules/master/service-list/routes.js";
import tpaRoutes from "./modules/master/tpa/routes.js";
import gipsaaCompanyRoutes from "./modules/master/gipsaa/routes.js";
import insuranceCompanyRoutes from "./modules/master/insurance/routes.js";
import governmentCompanyRoutes from "./modules/master/goverment-company/routes.js";
import corporateCompanyPublicRoutes from "./modules/master/corporate-company-public/routes.js";
import corporateCompanyPrivateRoutes from "./modules/master/corporate-company-private/routes.js";
import doctorScheduleRoutes from "./modules/User/doctor-schedule/routes.js";
import uhidRoutes from "./modules/UHID/routes.js";
import appointmentRoutes from "./modules/opd/appointment/routes.js";
import serviceRateRoutes from "./modules/master/service-rate/routes.js";

const app = express();

app.use(express.json());
app.use(cors());
app.use(helmet());

// routes will go here later
app.get("/", (req, res) => res.send("HMS MadeSimplified API running"));
app.use("/auth", authRoutes);
app.use("/doctor-schedule", doctorScheduleRoutes);
app.use("/appointment", appointmentRoutes);
app.use("/uhid", uhidRoutes);
app.use("/users", userRoutes);
app.use("/role", roleRoutes);
app.use("/ledger", ledgerRoutes);
app.use("/sub-ledger", subLedgerRoutes);
app.use("/payment-mode", paymentModeRoutes);
app.use("/payee-category", payeeCategoryRoutes);
app.use("/bill-group", billGroupRoutes);
app.use("/service-list", serviceListRoutes);
// app.use("/service-group", serviceGroupRoutes);
app.use("/tpa", tpaRoutes);
app.use("/gipsaa-company", gipsaaCompanyRoutes);
app.use("/insurance-company", insuranceCompanyRoutes);
app.use("/government-company", governmentCompanyRoutes);
app.use("/corporate-company-public", corporateCompanyPublicRoutes);
app.use("/corporate-company-private", corporateCompanyPrivateRoutes);
app.use("/prefix", prefixRoutes);
app.use("/diploma", diplomaRoutes);
app.use("/graduation", graduationRoutes);
app.use("/post-graduation", postGraduationRoutes);
app.use("/speciality", SuperSpecializationRoutes);
app.use("/council", councilRoutes);
app.use("/department-type", departmentTypeRoutes);
app.use("/department-sub-type", departmentSubTypeRoutes);
app.use("/department", departmentRoutes);
app.use("/designation", designationRoutes);
app.use("/service-rate", serviceRateRoutes);

export default app;
